/****************************************************************************

   Demonstration of File-Related Library Calls

****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main( void )
{
    /* Notes
    int L_tmpnam: macro val for minimum size of a string large enough 
                to hold a file name generated by the tmpnam() function

    FILE * tmpfile(): creates a temporary binary file, like "wb+"
                    deleted automatically when program terminates

    char* tmpnam(char *result): returns valid file name that does not refer
                to an existing file

    int sprintf(char *str, const char *format, ..): sends formatted output 
                to a string pointed to by str. if successfuk returns number 
                characters written, excluding the null-character at the end 
                of the string. Otherwise, negative number returned for failure.

    int putchar(int char): writes char to stdout
    int puts(const char *str): writes a string to stdout up to but not 
            including the null character. A new line is appended to the output.
   
    int fputs(const char *str, FILE *stream): writes a string to the specified stream
            up to but not including the null character. fputs allows specification
            of console


    int getchar(void): gets char from stdin. same as getc with stdin.
    int getc(FILE *stream): gets char from stream
    int fgetc(FILE *stream): pretty much the same as getc
        - all return EOF if error

    DOS Commands"
        type [filename] == unix cat filename
        dir             == unix ls

    */
    char filename[L_tmpnam]; // L_tmpnam defined in stdio.h
    char *strs[] = { "Hello\n", "Goodbye\n", "Cat\n", "Dog\n", NULL};
    char **mover = strs;
    char line[80], command[80];
    FILE *fp;

    // Open temporary file
    fp = tmpfile(); // opened in w+ mode
    for ( ; *mover != NULL; mover++) fputs(*mover, fp);
    fclose(fp);

    // Get name for a file that will not conflict with existing names
    if (tmpnam(filename) == NULL)
    // if(mkstemp(filename) == -1)
    {
        printf("Could not get non-conflicting filename.\n");
        exit(1);
    }
    printf("\nFilename obtained is: %s\n\n", filename);
    fp = fopen(filename, "w+");
    for (mover = strs; *mover != NULL; mover++) fputs(*mover, fp);
    rewind(fp);
    while (fgets(line, 80, fp)) printf("%s", line);
    putchar('\n');
    fclose(fp);
    getchar();

    // Is "filename" there?
    sprintf(command, "ls -l %s", filename);
    // sprintf(command, "type %s", filename);

    // system("dir");
    // system("ls");
    system(command);
    getchar();

    if (rename(filename, "garbage.txt") != 0)
    {
        printf("Could not rename: %s\n", filename);
        remove(filename);
        system(command); // file not found error?!
        exit(2);
    }
    system("ls -l garbage.txt");
    getchar();

    // If we got here rename succeeded
    // system("type garbage.txt");
    system("cat garbage.txt");
    return 0;
}
